# image: 'rust:latest'
image: 'clux/muslrust:stable'

stages:
  - test
  - doc
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose
  only:
    - master
    - tags

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=lowrr">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - tags

linux-musl:
  stage: build
  artifacts:
    expose_as: 'lowrr'
    paths: ['target/x86_64-unknown-linux-musl/release/lowrr']
  script:
    - cargo build --release --target x86_64-unknown-linux-musl
  only:
    - tags

cache:
  paths:
    - apt/
    - cargo/
    - target/
